---
- name: Setup dependencies for later installations
  ansible.builtin.apt:
    name: "{{ packages }}"
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - nfs-common
