---
- name: Generate a new kubeadm token
  ansible.builtin.command: kubeadm token create --print-join-command
  register: kube_token
  when: inventory_hostname in groups['masters']

- name: Set join_command
  ansible.builtin.set_fact:
    join_command: "{{ hostvars[groups['masters'][0]].kube_token.stdout }}"

- name: Join workers
  ansible.builtin.command: "sudo {{ join_command }}"
  register: join_worker
  until: join_worker.stdout.find("This node has joined the cluster") != -1
  retries: 2
  delay: 180
  when: inventory_hostname in groups['workers']
  ignore_errors: true

- name: Set role of workers
  environment:
    KUBECONFIG: "/etc/kubernetes/admin.conf"
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Node
      metadata:
        name: "{{ hostvars[item]['inventory_hostname'] }}"
        labels:
          kubernetes.io/role: worker
  with_items: "{{ groups['workers'] }}"
  when: inventory_hostname == hostvars[groups['masters'][0]].inventory_hostname
