---
- name: Update the package index
  ansible.builtin.apt:
    update_cache: true
    force_apt_get: true
  when: inventory_hostname in groups['masters']

- name: Wait for updates
  become: true
  ansible.builtin.shell: while sudo fuser /var/lib/dpkg/{{ item }} >/dev/null 2>&1; do sleep 1; done;
  with_items:
    - lock
    - lock-frontend
  when: inventory_hostname in groups['masters']

- name: Install HAProxy
  ansible.builtin.apt:
    name: haproxy
    state: present
  when: inventory_hostname in groups['masters']

- name: Add and enable HAProxy configuration
  ansible.builtin.template:
    src: haproxy_cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: '0755'
  when: inventory_hostname in groups['masters']
  notify:
    - Restart haproxy

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
